- name: Check dpkg lock when Server first start
  become: yes
  shell:  |
    while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
    while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;
    
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: True
    autoremove: yes
  when: common_system_upgrade and (init == '1' or init == 1)
  
- name: Check dpkg lock wait for Upgrade
  become: yes
  shell:  |
    while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
    while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;

- block:
  - name: Install Common Software
    apt: 
      name: [acl,mosh,curl,gnupg2,ca-certificates,lsb-release,wget,openssl,unzip,bzip2,expect,at,tree,vim,screen,pwgen,git,htop,imagemagick,goaccess,jq]
      state: latest
      force_apt_get: True
      allow_unauthenticated: yes
      
  - name: Install locate
    shell: |
      apt-get install mlocate
      updatedb
      
  when: common_install_components

- block:
  - name: Setting rc.local
    file:
      path: /etc/rc.local
      state: touch
      mode: 0750

  - name: Write rc.local
    shell: echo "#!/bin/bash" > /etc/rc.local

  - name: restart rc.local
    service: name=rc.local state=restarted enabled=yes
  when: common_set_rclocal
