- name: Wait for sudo
  become: yes
  shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
  
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: True
    autoremove: yes

- name: Install Common Software
  apt: 
    name: [mosh,curl,gnupg2,ca-certificates,lsb-release,wget,openssl,unzip,bzip2,expect,at,vim,screen,pwgen,git,htop,imagemagick,goaccess]
    state: latest
    force_apt_get: True
    allow_unauthenticated: yes
  when: common_install_components

- block:
  - name: Setting rc.local
    file:
      path: /etc/rc.local
      state: touch
      mode: 0750

  - name: Write rc.local
    shell: echo "#!/bin/bash" > /etc/rc.local

  - name: restart rc.local
    service: name=rc.local state=restarted enabled=yes
  when: common_set_rclocal
