- debug:
    msg: Will install components on {{ ansible_distribution }} 

- include: "{{ansible_os_family}}.yml"


# Python模块处理
- block:
  - name: pip upgrade
    shell: python{{ansible_python.version.major}} -m pip install -U pip
    
  - name: Install pip requirements module
    pip:
      name: [pexpect,PyMySQL]
      extra_args: "-U" 
  when: common_install_python_modules

# 系统设置
- block:
  - name: Set swapiness
    sysctl:
      name: vm.swappiness
      value: "10"

  - name: Fix No space left on device
    sysctl:
      name: fs.inotify.max_user_watches
      value: "8192000"
  when: ansible_distribution != 'OracleLinux'

# 准备基本目录
- block:
  - name: Create Dir
    file:
      path: '/data/{{item}}'
      state: directory
    with_items:
      - logs
      - config
      - cert
      - wwwroot
  when: ansible_distribution != 'OracleLinux'
  
# set a regular hostname
- block:
  - name: hostname rename
    shell: get_hostname=$(hostname);echo ${get_hostname%.*}
    register: common_get_hostname
  - hostname:
      name: {{common_get_hostname.stdout}}
