# Centos 更新 安装基础软件工具等操作
- block:
  - name: System Upgrade
    dnf: name=* state=latest

  - name: Disable SELinux
    selinux:
      state: disabled

  - name:  temporarily disable Selinux
    shell: setenforce 0 
    when: ansible_selinux.status != 'disabled'

  - name: Install Common Software
    dnf: 
      name: [mosh,wget,openssl,unzip,bzip2,expect,at,vim,screen,pwgen,git,htop,ImageMagick,inotify-tools,dnf-automatic]
    
  - name: Configuration dnf-automatic
    copy: src=automatic.conf dest=/etc/dnf/automatic.conf

  - name: Start dnf-automatic.timer
    service: name=dnf-automatic.timer enabled=yes
  
  when: ansible_distribution == 'CentOS'

# Ubuntu 更新 安装基础软件工具等操作
- block:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: True
      autoremove: yes

  - name: Install Common Software
    apt: 
      name: [mosh,curl,gnupg2,ca-certificates,lsb-release,wget,openssl,unzip,bzip2,expect,at,vim,screen,pwgen,git,htop,imagemagick,goaccess,unattended-upgrades]
      state: latest
      force_apt_get: True
      allow_unauthenticated: yes

  - name: Configuration unattended-upgrades
    copy: src=20auto-upgrades dest=/etc/apt/apt.conf.d/
  
  when: ansible_distribution == 'Ubuntu'

- name: pip requirements
  pip:
    name: pexpect

- name: Set swapiness
  sysctl:
    name: vm.swappiness
    value: "10"

- name: Fix No space left on device
  sysctl:
    name: fs.inotify.max_user_watches
    value: "8192000"

- name: Create Dir
  file:
    path: '/data/{{item}}'
    state: directory
  with_items:
    - logs
    - config
    - cert
