- name: System Upgrade
  yum: name=* state=latest

- name: Install Extra Packages for Enterprise Linux
  yum: 
    name: epel-release
  when: ansible_distribution != 'Amazon'

- name: Install Extra Packages for Enterprise Linux
  shell: amazon-linux-extras install epel -y
  when: ansible_distribution == 'Amazon'


- name: Install Common Software
  yum: 
    name: [mosh,wget,openssl,unzip,bzip2,expect,at,vim,screen,pwgen,git,htop,ImageMagick,inotify-tools,libselinux-python]
  
- shell: setenforce 0
  when: ansible_selinux.status != 'disabled'

- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_selinux.status != 'disabled'
  
- name: Install PiP
  yum:
    name: python-pip
  when: ansible_python.version.major == 2