- name: System Upgrade
  yum: name=* state=latest
  when: common_system_upgrade and (init == '1' or init == 1)

- name: Install Extra Packages for Enterprise Linux on {{ansible_distribution}}
  yum: 
    name: [epel-release,centos-release-scl]
    update_cache: yes
    state: latest
  when: ansible_distribution != 'Amazon' and ansible_distribution != 'OracleLinux'

- name: Install Extra Packages for Enterprise Linux on {{ansible_distribution}},there is [releaseserver] in the linux repo,so download from websoft9 self repo 
  shell: |
    amazon-linux-extras install epel -y
    wget -O /etc/yum.repos.d/CentOS7-Base.repo https://raw.githubusercontent.com/websoft9dev/role_common/master/files/CentOS7-Base.repo
  when: ansible_distribution == 'Amazon'

- block:
  - name: Install Common Software
    yum: 
      name: [mosh,wget,openssl,unzip,bzip2,expect,at,vim,screen,pwgen,git,htop,ImageMagick,inotify-tools,libselinux-python,yum-utils]
    when: ansible_distribution != 'OracleLinux'
  
  - name: intall mlocate
    shell: |
      yum install mlocate -y
      updatedb
  when: common_install_components and ansible_distribution != 'OracleLinux'
  
- name: Disable SELinux temporarily
  shell: sudo setenforce 0
  when: ansible_selinux.status != 'disabled'

- name: Disable SELinux ermanently
  selinux:
    state: disabled
  when: ansible_selinux.status != 'disabled'
  
- name: Setting rc.d 0750
  file:
    path: /etc/rc.d/rc.local
    mode: 0750
  when: common_set_rclocal
