- name: System Upgrade
  yum: name=* state=latest
  when: common_system_upgrade and (init == '1' or init == 1)

- name: Install Extra Packages for Enterprise Linux on {{ansible_distribution}}
  yum: 
    name: epel-release
  when: ansible_distribution != 'Amazon' and ansible_distribution != 'OracleLinux'

- name: Install Extra Packages for Enterprise Linux on {{ansible_distribution}}
  shell: amazon-linux-extras install epel -y
  when: ansible_distribution == 'Amazon'

- block:
  - name: Install Common Software
    yum: 
      name: [mosh,wget,openssl,unzip,bzip2,expect,at,vim,screen,pwgen,git,htop,ImageMagick,inotify-tools,libselinux-python]
    when: ansible_distribution != 'OracleLinux'

  when: common_install_components
  
- name: Disable SELinux temporarily
  shell: sudo setenforce 0
  when: ansible_selinux.status != 'disabled'

- name: Disable SELinux ermanently
  selinux:
    state: disabled
  when: ansible_selinux.status != 'disabled'
  
- name: Setting rc.d 0750
  file:
    path: /etc/rc.d/rc.local
    mode: 0750
  when: common_set_rclocal
