- name: Install snap tools
  apt: 
    name: snapd
    update_cache: yes
  when: ansible_os_family == "Debian" 

- name: Install snap tools
  yum: 
    name:
    update_cache: yes
  when: ansible_os_family == "RedHat"
